import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const payload = await req.json();

    const { data } = payload;

    // Only act when outcome contains 'needs follow-up' (case-insensitive)
    const outcome = (data?.outcome || "").toLowerCase();
    if (!outcome.includes("follow") && !outcome.includes("follow-up") && !outcome.includes("followup")) {
      return Response.json({ skipped: "outcome does not require follow-up" });
    }

    const customerId = data?.customer_id;
    const salesRep = data?.sales_rep || "";
    const interactionType = data?.interaction_type || "interaction";
    const summary = data?.summary || "No summary provided";

    // Fetch customer name for context
    let customerName = "Unknown Customer";
    if (customerId) {
      const customers = await base44.asServiceRole.entities.CustomerProfile.filter({ id: customerId });
      if (customers?.length > 0) customerName = customers[0].name;
    }

    // 1. Create a follow-up task assigned to the sales rep
    await base44.asServiceRole.entities.Task.create({
      title: `Sales Follow-Up: ${customerName}`,
      description: `Auto-generated by Sales Agent after a "${interactionType}" interaction.\n\nSummary: ${summary}\n\nOutcome: ${data?.outcome}`,
      status: "pending",
      priority: "high",
      assignee: salesRep,
      department: "Sales",
      due_date: (() => {
        const d = new Date();
        d.setDate(d.getDate() + 2);
        return d.toISOString().split("T")[0];
      })(),
      customer_id: customerId || "",
    });

    // 2. Notify the sales rep
    if (salesRep) {
      await base44.asServiceRole.entities.Notification.create({
        title: "Sales Follow-Up Required",
        message: `Your ${interactionType} with ${customerName} requires a follow-up. Check your tasks.`,
        type: "info",
        read: false,
        target_user: salesRep,
      });
    }

    // 3. Log the automation
    await base44.asServiceRole.entities.ActivityLog.create({
      action: "automation_triggered",
      description: `Sales Agent auto-created follow-up task for ${customerName} after "${interactionType}" logged with outcome: ${data?.outcome}`,
      user_name: "Sales Agent",
      entity_type: "SalesInteraction",
      entity_id: data?.id || "",
    });

    return Response.json({ success: true, customer: customerName });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});